'use client'

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { AlertCircle, CheckCircle, Clock } from 'lucide-react'

export function AbacAlerts() {
  const [alerts] = useState([
    {
      id: 'ABAC-001',
      type: 'Commission Anomaly',
      employee: 'Robert K.',
      amount: '$45,000',
      riskScore: 87,
      status: 'Open',
      date: '2024-06-15',
    },
    {
      id: 'ABAC-002',
      type: 'Government Interaction',
      employee: 'Ahmed K.',
      amount: '$5,000',
      riskScore: 91,
      status: 'Investigating',
      date: '2024-06-14',
    },
    {
      id: 'ABAC-003',
      type: 'Third-Party Risk',
      employee: 'Lisa M.',
      amount: '$12,000',
      riskScore: 76,
      status: 'Under Review',
      date: '2024-06-13',
    },
    {
      id: 'ABAC-004',
      type: 'Expense Violation',
      employee: 'David L.',
      amount: '$8,500',
      riskScore: 82,
      status: 'Resolved',
      date: '2024-06-12',
    },
  ])

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Open':
        return <AlertCircle className="h-4 w-4 text-red-500" />
      case 'Investigating':
        return <Clock className="h-4 w-4 text-amber-500" />
      case 'Under Review':
        return <Clock className="h-4 w-4 text-blue-500" />
      case 'Resolved':
        return <CheckCircle className="h-4 w-4 text-green-500" />
      default:
        return null
    }
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>ABAC Alerts</CardTitle>
          <CardDescription>All alerts generated by the surveillance system</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Alert ID</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Employee</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Risk Score</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {alerts.map((alert) => (
                <TableRow key={alert.id}>
                  <TableCell className="font-mono font-medium">{alert.id}</TableCell>
                  <TableCell>{alert.type}</TableCell>
                  <TableCell>{alert.employee}</TableCell>
                  <TableCell>{alert.amount}</TableCell>
                  <TableCell>
                    <Badge
                      variant={
                        alert.riskScore >= 80
                          ? 'destructive'
                          : alert.riskScore >= 60
                          ? 'secondary'
                          : 'default'
                      }
                    >
                      {alert.riskScore}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center space-x-2">
                      {getStatusIcon(alert.status)}
                      <span>{alert.status}</span>
                    </div>
                  </TableCell>
                  <TableCell>{alert.date}</TableCell>
                  <TableCell>
                    <Button variant="outline" size="sm">View Details</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
